public with sharing class add {
    public add() {

    }
     public static void addition(Integer x, Integer y)
     {
         Integer z=x+y;
     }
     public static void substraction(Integer a, Integer b)
     {
         Integer c=a-b;
     }
     public static void multiply(Integer a, Integer b)
     {
         Integer c=a*b;
     }
     public static void division(Integer n, Integer m)
     {
         Integer o=m/n;
     }
     public static void modulus(Integer n, Integer m)
     {
         Integer o=m/n;
     }
}
